version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: ${CONTAINER_NAME}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USR}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PWD}
    networks:
      - mongodb
    volumes:
      - ${DB_PATH}:/var/lib/cassandra
      - ./scripts/:/scripts/

networks:
  mongodb:
    name: PostRelationalDatabases__Labs.Mongodb
