execute:
	docker exec PostRelationalDatabases__Labs.Cassandra cqlsh --file /scripts/init.cql

run:
	docker compose up --detach

connect:
	docker exec -it PostRelationalDatabases__Labs.Cassandra /bin/bash

